name: Make AppMaps

on:
  pull_request:
  workflow_dispatch:
    inputs:
      var1:
        description: 'Input variable 1'
        required: true
        default: 'default_value1'
      var2:
        description: 'Input variable 2'
        required: true
        default: 'default_value2'

jobs:
  run:
    runs-on: swe-bench-ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Create conda env
      run: |
        conda init bash
        conda env create -f environment.yml
    - name: Build submodules
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        cd submodules/appmap-js
        git checkout -- .
        yarn
        yarn build
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1