name: Make AppMaps

on:
  pull_request:
  workflow_dispatch:
    inputs:
      var1:
        description: 'Input variable 1'
        required: true
        default: 'default_value1'
      var2:
        description: 'Input variable 2'
        required: true
        default: 'default_value2'

jobs:
  run:
    runs-on: swe-bench-ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get submodule commit hash
      id: get-submodule-hash
      run: |
        submodule_commit=$(git submodule status submodules/appmap-js | awk '{print $1}')
        echo "submodule-commit=$submodule_commit" >> $GITHUB_ENV

    - name: Cache submodule directory
      uses: actions/cache@v3
      with:
        path: submodules/
        key: submodule-cache-${{ env.submodule_commit }}

    - name: Set up Python
      uses: actions/setup-python@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        environment-file: ./environment.yml
        activate-environment: swe-bench
        python-version: 3.10
        use-only-tar-bz2: true

    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('etc/example-environment.yml') }}

    - name: Build submodules
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        cd submodules/appmap-js
        git checkout -- .
        yarn
        yarn build
    
    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1