name: Make AppMaps

on:
  pull_request:
  workflow_dispatch:
    inputs:
      projectFilter:
        description: 'Project or instance to filter for'
        required: true

jobs:
  run:
    runs-on: swe-bench-ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get submodule commit hash
      id: get-submodule-hash
      run: |
        submodule_commit=$(git submodule status submodules/appmap-js | awk '{print $1}')
        echo "submodule-commit=$submodule_commit" >> $GITHUB_ENV

    - name: Cache submodule directory
      id: submodule-cache
      uses: actions/cache@v3
      with:
        path: submodules/
        key: submodule-cache-${{ env.submodule-commit }}

    - name: Cache conda
      id: cache-conda
      uses: actions/cache@v3
      env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('./environment.yml') }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
        cache: 'pip'
   
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ./environment.yml
        activate-environment: swe-bench
        python-version: 3.9
        use-only-tar-bz2: true

    - name: Build submodules
      if: steps.submodule-cache.outputs.cache-hit != 'true'
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        cd submodules/appmap-js
        git checkout -- .
        yarn
        yarn build
    
    - name: Make dirs
      run: |
        mkdir appmaps appmap_logs /tmp/swe-appmaps 

    - name: Make Appmaps
      run: |
        ./appmap/make_appmaps-github-actions.sh --filter pyvista__pyvista-4315

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: project-filter-${{ github.event.inputs.projectFilter }}
        path: ./appmaps/