name: Make AppMaps

on:
  pull_request:
  workflow_dispatch:
    inputs:
      projectFilter:
        description: 'Project or instance to filter for'
        required: true

jobs:
  run:
    runs-on: swe-bench-ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache conda
      id: cache-conda
      uses: actions/cache@v3
      env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('./environment.yml') }}
    
    - name: Install AppMap tools
      uses: getappmap/install-action@v1
      with:
        install-appmap-library: false
        tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-v3.147.0/appmap-linux-x64

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
        cache: 'pip'
   
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ./environment.yml
        activate-environment: swe-bench
        python-version: 3.9

    - name: Make dirs
      run: |
        mkdir appmaps appmap_logs /tmp/swe-appmaps 

    - name: Make Appmaps
      run: |
        ./appmap/make_appmaps-github-actions.sh --filter matplotlib__matplotlib-25433

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        path: | 
          ./appmaps/*.tar.gz
          ./appmap_logs/