name: Make AppMaps (delete me before we merge)

on:
  pull_request:

permissions:
  contents: write
  actions: write

jobs:
  run:
    runs-on: SWE-Bench_Larger
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install AppMap tools
      uses: getappmap/install-action@v1
      with:
        install-appmap-library: false
        tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-v3.147.0/appmap-linux-x64

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
   
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9

    - name: Make dirs
      run: |
        mkdir -p appmaps appmap_logs /tmp/swe-appmaps
        
    - name: Create conda env
      run: |
        conda init bash
        conda env create -f environment.yml

    - name: Make Appmaps
      run: |
          source /home/runner/.bashrc
          conda activate swe-bench
          conda info
          APPMAP_MAX_EVENTS=10000 ./appmap/make_appmaps-github-actions.sh --filter pydicom__pydicom-1694

    - name: Get Artifact Name
      id: get-artifact-name  # Add an ID for this step
      run: |
        file=$(ls appmaps/ | head -n 1)
        echo "file_name=$file" >> $GITHUB_ENV
        echo "::set-output name=file_name::$file" 

    - name: Upload AppMaps
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.get-artifact-name.outputs.file_name }}  # Use the output from the previous step
        path: ./appmaps/${{ steps.get-artifact-name.outputs.file_name }}
        compression-level: 0 # no compression

    - name: Upload SWE Bench Logs
      uses: actions/upload-artifact@v4
      with:
        name: appmap-logs.zip
        path: ./appmap_logs/

    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      if: ${{ failure() }}
      with:
        wait-timeout-minutes: 5