name: Make AppMaps

on:
  pull_request:
  workflow_dispatch:
    inputs:
      var1:
        description: 'Input variable 1'
        required: true
        default: 'default_value1'
      var2:
        description: 'Input variable 2'
        required: true
        default: 'default_value2'

jobs:
  run:
    runs-on: swe-bench-ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get submodule commit hash
      id: get-submodule-hash
      run: |
        submodule_commit=$(git submodule status submodules/appmap-js | awk '{print $1}')
        echo "submodule-commit=$submodule_commit" >> $GITHUB_ENV

    - name: Cache submodule directory
      uses: actions/cache@v3
      with:
        path: submodules/
        key: submodule-cache-${{ env.submodule_commit }}

    - name: Set up Python
      uses: actions/setup-python@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.8

    - name: Cache Conda environment
      uses: actions/cache@v3
      id: conda-cache
      with:
        path: ~/.conda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Create Conda environment
      if: steps.conda-cache.outputs.cache-hit != 'true'
      run: |
        conda env create -f environment.yml

    - name: Activate Conda environment
      run: |
        source ~/.bashrc
        conda activate swe-bench

    - name: Verify Conda environment
      run: |
        conda list
    
    - name: Build submodules
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        cd submodules/appmap-js
        git checkout -- .
        yarn
        yarn build
    
    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1